config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :bachelorettes, only: [:show] do
    resources :contestants, only: [:index, :show]
    # resources :outings, only: [:show]
  end
  resources :outings, only: [:show] do
    resources :contestants, only: [:destroy], controller: "contestant_outings"
  end
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bachelorette.rb
class Bachelorette < ApplicationRecord
  has_many :contestants
  
end

app/models/contestant.rb
class Contestant < ApplicationRecord
  belongs_to :bachelorette
  has_many :contestant_outings
  has_many :outings, through: :contestant_outings
end

app/models/contestant_outing.rb
class ContestantOuting < ApplicationRecord
  belongs_to :contestant
  belongs_to :outing
end

app/models/outing.rb
class Outing < ApplicationRecord
  has_many :contestant_outings
  has_many :contestants, through: :contestant_outings

  def count_contestants
    contestants.count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bachelorettes_controller.rb
class BachelorettesController < ApplicationController
  def show 
    @bachelorette = Bachelorette.find(params[:id])
  end
end

app/controllers/contestant_outings_controller.rb
class ContestantOutingsController < ApplicationController
  def destroy
    contestant_outings = ContestantOuting.find_by(outing_id: params[:outing_id], contestant_id:  params[:id])

    contestant_outings.delete

    redirect_to outing_path(params[:outing_id])
  end
end

app/controllers/contestants_controller.rb
class ContestantsController < ApplicationController
  def index
    @bachelorette = Bachelorette.find(params[:bachelorette_id])
    # @contestants = @bachelorette.contestants
  end

  def show
    @contestant = Contestant.find(params[:id])
  end
end

app/controllers/outings_controller.rb
class OutingsController < ApplicationController
  def show 
    @outing = Outing.find(params[:id])
  end

  def destroy
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bachelorettes/show.html.erb
<h1><%= @bachelorette.name %></h1>

<h3>Season <%= @bachelorette.season_number %> - <%= @bachelorette.season_description %></h3>


<%= link_to "Contestants", bachelorette_contestants_path(@bachelorette)  %>  

app/views/contestants/index.html.erb
<h1><%= @bachelorette.name%>'s Contestants</h1>

<% @bachelorette.contestants.each do |contestant|%>
  <p><%= link_to contestant.name, bachelorette_contestant_path(@bachelorette, contestant) %></p>
  <p><%= contestant.age %></p>
  <p><%= contestant.hometown %></p>
<% end %>

app/views/contestants/show.html.erb
<h1><%= @contestant.name %></h1>

<p>Season <%= @contestant.bachelorette.season_number %> - <%= @contestant.bachelorette.season_description  %></p>

<p>Outings: <% @contestant.outings.each do |outing|  %></p>
<p><%= link_to outing.name, outing_path(outing)  %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheFinalRose</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/outings/show.html.erb
<h1><%= @outing.name  %></h1>

<h3>Location: <%= @outing.location %></h3>
<h3>Date: <%= @outing.date %></h3>
<h3>Contestants: <%= @outing.count_contestants %></h3>
<% @outing.contestants.each do |contestant| %>
  <div id="contestant_<%=contestant.id%>">
    <p><%= contestant.name%>
    <%= button_to "Remove", outing_contestant_path(@outing, contestant), method: :delete %>
    </p>

  </div>
<% end %>